// main/love_admin_page.h —— 由 tools/gen_admin_page.py 生成,请勿手改。
// 模板在 assets/web/admin.{html,css,js},字体与图标见 main/love_web_assets.h。
// 三个资源分开返回,理由见生成脚本的文档字符串(单次响应太大会被 socket 超时掐断)。
#pragma once

static const char LOVE_ADMIN_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<title>纪念日 · 后台</title>\n"
    "<!-- 样式、脚本、底纹是独立小资源,不内联。图标的 data URI 内联在 admin.js 里 ——\n"
    "     十几条 /icon/N.png 会多开一堆连接,不值得。\n"
    "     页面图标必须在 HTML 里声明:浏览器会自己去找 /favicon.ico 和\n"
    "     /apple-touch-icon*.png,那两个路径只能靠路由应答,不像 data URI 能内联。 -->\n"
    "<link rel=\"icon\" href=\"/favicon.ico\">\n"
    "<link rel=\"apple-touch-icon\" href=\"/apple-touch-icon.png\">\n"
    "<link rel=\"stylesheet\" href=\"/admin.css\">\n"
    "<script src=\"/admin.js\" defer></script>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"grid\">\n"
    "  <h1>纪念日 · 后台\n"
    "    <small>设备 <span id=\"deviceName\">--</span> ｜ 本页与设备界面同素材、同配色</small>\n"
    "  </h1>\n"
    "\n"
    "  <div class=\"card\">\n"
    "    <h2>设备预览 <span class=\"row\" style=\"flex:0 0 auto; gap:6px\">\n"
    "      <button class=\"ghost\" id=\"pvMain\" type=\"button\">主屏</button>\n"
    "      <button class=\"ghost\" id=\"pvEvent\" type=\"button\">事件卡</button>\n"
    "    </span></h2>\n"
    "    <div class=\"device\">\n"
    "      <div class=\"screen\" id=\"screen\">\n"
    "        <div class=\"s-battery\">\n"
    "          <span class=\"bat-shell\"><i id=\"pvBatFill\"></i></span>\n"
    "          <span id=\"pvBattery\">-- %</span>\n"
    "        </div>\n"
    "        <div class=\"el s-page\" id=\"pvEventPage\" style=\"display:none\">1/1</div>\n"
    "        <div id=\"pvMainView\">\n"
    "          <div class=\"s-person\" id=\"pvPersonA\" style=\"left:calc(14px * var(--s))\">\n"
    "            <img id=\"pvIconA\" alt=\"\"><span id=\"pvNameA\">--</span>\n"
    "          </div>\n"
    "          <div class=\"s-person\" id=\"pvPersonB\" style=\"left:calc(130px * var(--s))\">\n"
    "            <img id=\"pvIconB\" alt=\"\"><span id=\"pvNameB\">--</span>\n"
    "          </div>\n"
    "          <div class=\"el s-title\">在一起</div>\n"
    "          <div class=\"el s-big\" id=\"pvDays\">--</div>\n"
    "          <div class=\"el s-unit\" id=\"pvUnit\">天</div>\n"
    "          <div class=\"s-divider\"></div>\n"
    "          <div class=\"el s-date\" id=\"pvStart\">起始日 ----</div>\n"
    "        </div>\n"
    "        <div id=\"pvEventView\" style=\"display:none\">\n"
    "          <div class=\"el s-event-icon\"><img id=\"pvEventIcon\" alt=\"\"></div>\n"
    "          <div class=\"el s-event-name\" id=\"pvEventName\">--</div>\n"
    "          <div class=\"el s-event-big\" id=\"pvEventDays\">--</div>\n"
    "          <div class=\"el s-event-unit\" id=\"pvEventUnit\">天后</div>\n"
    "          <div class=\"el s-event-date\" id=\"pvEventDate\">目标日 ----</div>\n"
    "        </div>\n"
    "        <div class=\"el s-hint\" id=\"pvHint\">上/下 切换 · 长按确定 设置</div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <p class=\"muted\">预览按真机 240×320 坐标逐项摆放，只等比缩放；天数和单位由本页按与设备一致的规则即时计算，最终以设备显示为准。</p>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"card\">\n"
    "    <h2>在一起</h2>\n"
    "    <label for=\"start\">起始日</label>\n"
    "    <input type=\"date\" id=\"start\">\n"
    "    <div class=\"row\" style=\"margin-top:12px\">\n"
    "      <div>\n"
    "        <label for=\"nameA\">第一个人</label>\n"
    "        <input type=\"text\" id=\"nameA\" maxlength=\"8\" placeholder=\"名字\">\n"
    "      </div>\n"
    "      <div>\n"
    "        <label for=\"nameB\">第二个人</label>\n"
    "        <input type=\"text\" id=\"nameB\" maxlength=\"8\" placeholder=\"名字\">\n"
    "      </div>\n"
    "    </div>\n"
    "    <label>第一个人头像</label><div class=\"icons\" id=\"iconsA\"></div>\n"
    "    <label>第二个人头像</label><div class=\"icons\" id=\"iconsB\"></div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"card\">\n"
    "    <h2>显示</h2>\n"
    "    <label for=\"blankOff\">自动熄屏</label>\n"
    "    <select id=\"blankOff\">\n"
    "      <option value=\"15\">15 秒</option>\n"
    "      <option value=\"30\">30 秒</option>\n"
    "      <option value=\"60\">1 分钟</option>\n"
    "      <option value=\"180\">3 分钟</option>\n"
    "      <option value=\"0\">常亮（不熄屏）</option>\n"
    "    </select>\n"
    "    <p class=\"muted\">到时间后关背光省电，按任意键唤醒 —— 唤醒那一下只负责亮屏，不会顺带改到日期。设备设置页里也能改。</p>\n"
    "    <p class=\"muted\">事件怎么显示是<b>每条自己选</b>的（见下面事件卡里的“展示”）：选“列表”的会一起出现在设备的列表屏上，\n"
    "      一屏 4 条、分页、按分类分组；选“单页”的自己独占一屏。设备上按上/下会依次走过\n"
    "      主屏 → 列表屏 → 各个单页 → 回到主屏，绕成一个圈。</p>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"card\">\n"
    "    <h2>倒计时事件 <span class=\"muted\" id=\"eventCount\"></span></h2>\n"
    "    <div id=\"events\"></div>\n"
    "    <div class=\"row\" style=\"margin-top:12px\">\n"
    "      <button type=\"button\" class=\"accent\" id=\"addEvent\">＋ 添加事件</button>\n"
    "    </div>\n"
    "    <datalist id=\"categoryOptions\"></datalist>\n"
    "    <p class=\"muted\">“每年重复”适合生日和节日，会自动折算到下一次发生日；“仅一次”用于具体的纪念日，过期后显示已过天数。\n"
    "      <b>分类</b>留空表示不分类，填过的分类名会在输入时提示；<b>展示</b>决定这条是进列表屏还是自己占一屏。\n"
    "      设备上<b>不能改日期</b>，都在这里改；卡片可以“收起”把长列表压短再上下移。</p>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"card\">\n"
    "    <h2>时间</h2>\n"
    "    <div class=\"kv\"><span>设备时间</span><b id=\"timeText\">--</b></div>\n"
    "    <div class=\"kv\"><span>状态</span><b><span class=\"pill\" id=\"timePill\">--</span></b></div>\n"
    "    <div class=\"row\" style=\"margin-top:12px\">\n"
    "      <button type=\"button\" class=\"primary\" id=\"syncTime\">用手机当前时间对时</button>\n"
    "    </div>\n"
    "    <p class=\"muted\">设备没有时钟。联网后会自动走 SNTP；也可以点上面的按钮用手机时间来对时（不依赖外网）。\n"
    "      没有网络也没有手机浏览器时，还能用蓝牙串口敲 <code>time &lt;Unix 秒&gt;</code> 对时。</p>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"card\">\n"
    "    <h2>网络与热点</h2>\n"
    "    <div class=\"kv\"><span>网络状态</span><b><span class=\"pill\" id=\"netPill\">--</span></b></div>\n"
    "    <div class=\"kv\"><span>IP 地址</span><b id=\"netIp\">--</b></div>\n"
    "    <div class=\"kv\"><span>已配置 Wi-Fi</span><b id=\"netSsid\">--</b></div>\n"
    "    <div class=\"kv\"><span>热点地址</span><b id=\"netUrl\">--</b></div>\n"
    "    <div class=\"kv\"><span>局域网地址</span><b id=\"netLanUrl\">--</b></div>\n"
    "    <div class=\"kv\"><span>热点</span><b id=\"apInfo\">--</b></div>\n"
    "    <div class=\"row\" style=\"margin-top:12px\">\n"
    "      <button type=\"button\" class=\"ghost\" id=\"scanBtn\">扫描附近 Wi-Fi</button>\n"
    "      <button type=\"button\" class=\"ghost\" id=\"apOn\">开热点</button>\n"
    "      <button type=\"button\" class=\"ghost\" id=\"apOff\">关热点</button>\n"
    "    </div>\n"
    "    <ul class=\"scan\" id=\"scanList\"></ul>\n"
    "    <label for=\"wifiSsid\">Wi-Fi 名称（2.4G）</label>\n"
    "    <input type=\"text\" id=\"wifiSsid\" placeholder=\"点上面的扫描结果可直接填入\">\n"
    "    <label for=\"wifiPass\">Wi-Fi 密码</label>\n"
    "    <input type=\"password\" id=\"wifiPass\" placeholder=\"密码不会回显，也不会出现在日志里\">\n"
    "    <div class=\"row\" style=\"margin-top:12px\">\n"
    "      <button type=\"button\" class=\"primary\" id=\"wifiSave\">保存并连接</button>\n"
    "      <button type=\"button\" class=\"ghost\" id=\"wifiClear\">清除凭据</button>\n"
    "    </div>\n"
    "    <p class=\"muted\">清除凭据后设备会重新打开热点，便于重新配置。热点默认开启 5 分钟无操作后自动关闭。\n"
    "      局域网地址由路由器 DHCP 分配，随时可能变化；这里显示的是设备当前实际持有的地址。</p>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"card\">\n"
    "    <h2>蓝牙串口</h2>\n"
    "    <label for=\"bleEnabled\">蓝牙</label>\n"
    "    <select id=\"bleEnabled\">\n"
    "      <option value=\"1\">开（可用手机 App 连上敲命令）</option>\n"
    "      <option value=\"0\">关（出厂默认，省内存）</option>\n"
    "    </select>\n"
    "    <p class=\"muted\">打开后设备广播成 <b>LoveCount-XXXX</b>，用手机上的 BLE 串口 App（Serial Bluetooth Terminal、\n"
    "      nRF Connect 等）连上就能敲命令，命令集与 USB 串口控制台完全一样：<code>help</code>、<code>status</code>、\n"
    "      <code>wifi &lt;名称&gt; &lt;密码&gt;</code>、<code>time &lt;Unix 秒&gt;</code>、<code>ble off</code>。\n"
    "      用的是标准 NUS 服务（服务 <code>6E400001-…</code>，写入 <code>6E400002-…</code>，通知 <code>6E400003-…</code>），\n"
    "      常见 App 都直接认，不用手配 UUID。</p>\n"
    "    <p class=\"muted\">蓝牙默认关闭，关着时不占内存也没有任何功能受影响；打开后一直没人连接的话，5 分钟会自动关闭并把这里改回「关」。</p>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"card\">\n"
    "    <h2>保存</h2>\n"
    "    <div class=\"row\">\n"
    "      <button type=\"button\" class=\"primary\" id=\"save\">保存到设备</button>\n"
    "      <button type=\"button\" class=\"ghost\" id=\"reload\">放弃改动</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "<div class=\"toast\" id=\"toast\"></div>\n"
    "</body>\n"
    "</html>\n";
#define LOVE_ADMIN_HTML_SIZE (sizeof(LOVE_ADMIN_HTML) - 1)

static const char LOVE_ADMIN_CSS[] =
    "/* assets/web/admin.css —— 后台网页样式,由设备以 /admin.css 单独返回。\n"
    "   底纹 /bg.png 是独立资源,不再以 data URI 内联。 */\n"
    ":root{\n"
    "  --pink:#F1959E; --pink-deep:#EAA5AC; --paper:#F4F4EA; --ink:#17202A;\n"
    "  --red:#E43B2F; --yellow:#FFD928; --green:#82BE2D; --muted:#9E9E9E;\n"
    "  --shadow:#C96F79; --bat-text:#FFE3E6;\n"
    "}\n"
    "*{box-sizing:border-box}\n"
    "body{\n"
    "  margin:0; padding:18px 14px 60px;\n"
    "  font-family:\"PingFang SC\",\"Hiragino Sans GB\",\"Microsoft YaHei\",sans-serif;\n"
    "  color:var(--ink);\n"
    "  background-color:var(--pink);\n"
    "  background-image:url(\"/bg.png\");\n"
    "  background-size:96px 96px;\n"
    "  image-rendering:pixelated;\n"
    "}\n"
    "h1{\n"
    "  font-size:20px; margin:0 0 14px; padding:12px 14px;\n"
    "  background:var(--paper); border:4px solid var(--ink);\n"
    "  box-shadow:6px 6px 0 var(--ink); letter-spacing:1px;\n"
    "}\n"
    "h1 small{display:block; font-size:12px; font-weight:400; color:#4a4a4a; margin-top:6px; letter-spacing:0}\n"
    ".grid{display:grid; gap:16px; grid-template-columns:1fr; max-width:760px; margin:0 auto}\n"
    ".card{\n"
    "  background:var(--paper); border:4px solid var(--ink);\n"
    "  box-shadow:6px 6px 0 var(--ink); padding:14px;\n"
    "}\n"
    ".card h2{\n"
    "  font-size:15px; margin:0 0 12px; padding-bottom:8px;\n"
    "  border-bottom:4px solid var(--ink); display:flex; justify-content:space-between; align-items:center;\n"
    "}\n"
    "label{display:block; font-size:13px; margin:10px 0 4px}\n"
    "input,select,button,textarea{font-family:inherit; font-size:14px}\n"
    "input[type=text],input[type=date],input[type=password],select{\n"
    "  width:100%; padding:9px 10px; background:#fff;\n"
    "  border:3px solid var(--ink); border-radius:0; color:var(--ink);\n"
    "}\n"
    "button{\n"
    "  padding:9px 14px; background:var(--paper); color:var(--ink);\n"
    "  border:3px solid var(--ink); border-radius:0; box-shadow:3px 3px 0 var(--ink);\n"
    "  cursor:pointer; font-weight:600;\n"
    "}\n"
    "button:active{transform:translate(2px,2px); box-shadow:1px 1px 0 var(--ink)}\n"
    "button.primary{background:var(--red); color:#fff}\n"
    "button.accent{background:var(--yellow)}\n"
    "button.ghost{background:#fff}\n"
    ".row{display:flex; gap:10px; flex-wrap:wrap; align-items:center}\n"
    ".row>*{flex:1 1 auto}\n"
    ".muted{color:#5a5a5a; font-size:12px}\n"
    ".icons{display:grid; grid-template-columns:repeat(8,1fr); gap:6px; margin-top:6px}\n"
    "/* .icons 的 display 会盖掉 hidden 的 UA 样式，收起必须显式写。 */\n"
    ".icons[hidden]{display:none}\n"
    ".icons button{\n"
    "  padding:4px; background:#fff; box-shadow:none; border:3px solid transparent;\n"
    "}\n"
    ".icons button.sel{border-color:var(--red); background:#FFE3E6}\n"
    ".icons img{width:100%; image-rendering:pixelated; display:block}\n"
    "/* 事件的头像选择器默认收起：每条都常驻展开会让手机端页面长出好几屏。 */\n"
    ".iconrow{display:flex; align-items:center; gap:8px; margin-top:6px}\n"
    ".iconcur{\n"
    "  width:46px; padding:4px; background:#fff; box-shadow:none; border:3px solid var(--ink);\n"
    "}\n"
    ".iconcur img{width:100%; image-rendering:pixelated; display:block}\n"
    "/* 头像的轻圆角,半径 4px 必须与 main/love_app.c 的 AVATAR_CORNER_RADIUS 一致\n"
    "   (它的判定式在 main/ui_pixel_math.c 的 ui_pixel_corner_cut(),有主机测试)。\n"
    "   **只给自定义头像加**:内置图标是透明背景的图形,四角有描边,给它加圆角会切到描边,\n"
    "   而设备端刻意不切(见 assets/images/love_pixel_art_gen.py 顶部的说明),两端要对齐。\n"
    "   设备预览里随 --s 一起缩放。 */\n"
    ".icons img.rounded,.iconcur img.rounded{border-radius:4px}\n"
    ".screen .s-person img.rounded,.screen .s-event-icon img.rounded{\n"
    "  border-radius:calc(4px * var(--s));\n"
    "}\n"
    "/* 自定义头像槽位：空槽显示\"＋\"，点一下直接选图上传 */\n"
    ".icons button.empty{border-style:dashed; border-color:#bbb; background:#FAFAF4}\n"
    ".icons button.empty .plus{\n"
    "  display:block; font-size:22px; line-height:1; color:#8a8a8a; padding:6px 0;\n"
    "}\n"
    ".icons .avabar{\n"
    "  grid-column:1 / -1; display:flex; align-items:center; gap:8px; flex-wrap:wrap;\n"
    "  margin-top:8px; padding-top:8px; border-top:2px dashed #bbb;\n"
    "}\n"
    ".icons .avabar .muted{font-size:12px}\n"
    ".event{border:3px dashed var(--ink); padding:10px; margin-top:12px; background:#fff}\n"
    ".event .head{display:flex; justify-content:space-between; align-items:center; font-size:13px; font-weight:700}\n"
    "/* 事件卡标题右侧的一排操作。刻意不用 .row —— .row>*{flex:1 1 auto} 会把按钮拉满整行。 */\n"
    ".event .headbtns{display:flex; gap:6px; align-items:center; flex:0 0 auto}\n"
    ".event .headbtns button{padding:4px 8px; font-size:13px; font-weight:600}\n"
    ".event .headbtns button:disabled{opacity:.35; cursor:default; box-shadow:2px 2px 0 #bbb}\n"
    "/* 收起时只留标题行。hidden 属性在 div 上默认生效,这里显式写是为了和 .icons 一致。 */\n"
    ".event .body[hidden]{display:none}\n"
    ".kv{display:flex; justify-content:space-between; font-size:13px; padding:4px 0; border-bottom:1px dashed #bbb}\n"
    ".kv:last-child{border-bottom:0}\n"
    ".kv b{font-weight:600}\n"
    ".scan li{display:flex; justify-content:space-between; gap:8px; padding:7px 0; border-bottom:1px dashed #bbb; font-size:13px; cursor:pointer}\n"
    ".scan li:hover{background:#FFE3E6}\n"
    "ul{list-style:none; margin:8px 0 0; padding:0}\n"
    ".toast{\n"
    "  position:fixed; left:50%; bottom:22px; transform:translateX(-50%);\n"
    "  background:var(--ink); color:#fff; padding:10px 16px; border:3px solid #fff;\n"
    "  font-size:13px; opacity:0; transition:opacity .2s; pointer-events:none; max-width:90vw;\n"
    "}\n"
    ".toast.show{opacity:1}\n"
    "/* 设备预览：坐标、字号、行高、素材尺寸全部按真机 240x320 的逻辑像素写，\n"
    "   并用 --s 统一缩放。改设备端 layout 时同步改这里的数值即可，不要再凭观感调。\n"
    "   字号只有 12 / 24 / 36 三种，对应真机那三套像素字库 —— 不要随手加第四种。\n"
    "   字形本身用系统字体（曾经内嵌 122 KB 的方舟像素字体子集换取'像素味'，\n"
    "   但那是一个比 HTML 本身大二十倍的响应，在热点上不值得；坐标对得上、\n"
    "   字号对得上，版式就是准的）。 */\n"
    ".device{\n"
    "  --s:1;                       /* 1 = 与真机 1:1；调小则整体等比缩小 */\n"
    "  width:calc(240px * var(--s) + 28px); margin:0 auto; padding:10px; background:#3b3b3b;\n"
    "  border:4px solid var(--ink); box-shadow:6px 6px 0 var(--ink);\n"
    "}\n"
    ".screen{\n"
    "  width:calc(240px * var(--s)); height:calc(320px * var(--s));\n"
    "  position:relative; overflow:hidden;\n"
    "  background-color:var(--pink); background-image:url(\"/bg.png\");\n"
    "  background-size:calc(48px * var(--s)) calc(48px * var(--s));\n"
    "  color:#fff;\n"
    "  font-family:\"PingFang SC\",\"Hiragino Sans GB\",\"Microsoft YaHei\",sans-serif;\n"
    "  image-rendering:pixelated;\n"
    "}\n"
    ".screen .el{position:absolute; left:0; right:0; text-align:center; color:#fff; white-space:nowrap}\n"
    "/* 真机: 电量一行(外壳 22x11 白框 + 粉色电量格 + 文字) TOP_RIGHT(-6,6)，12px */\n"
    ".screen .s-battery{\n"
    "  left:auto; right:calc(6px * var(--s)); top:calc(6px * var(--s));\n"
    "  position:absolute; display:flex; align-items:center; gap:calc(4px * var(--s));\n"
    "  font-size:calc(12px * var(--s)); line-height:calc(11px * var(--s));\n"
    "  color:var(--bat-text); white-space:nowrap;\n"
    "}\n"
    ".screen .bat-shell{\n"
    "  position:relative; display:block; box-sizing:border-box;\n"
    "  width:calc(22px * var(--s)); height:calc(11px * var(--s));\n"
    "  border:calc(2px * var(--s)) solid #fff; border-radius:calc(2px * var(--s));\n"
    "}\n"
    ".screen .bat-shell i{\n"
    "  position:absolute; left:0; top:0; bottom:0; width:0; background:#F7BFC4;\n"
    "}\n"
    "/* 真机: 人物框 96x100 置于 (中心-48, 34)，头像 40² 居中，名字在框内 y=46 */\n"
    ".screen .s-person{\n"
    "  position:absolute; top:calc(34px * var(--s)); width:calc(96px * var(--s));\n"
    "  text-align:center; color:#fff;\n"
    "}\n"
    ".screen .s-person img{\n"
    "  width:calc(40px * var(--s)); height:calc(40px * var(--s));\n"
    "  image-rendering:pixelated; display:block; margin:0 auto;\n"
    "}\n"
    ".screen .s-person span{\n"
    "  display:block; margin-top:calc(6px * var(--s));\n"
    "  font-size:calc(24px * var(--s)); line-height:calc(22px * var(--s));\n"
    "}\n"
    "/* 真机: 标题 TOP_MID y=120，24px */\n"
    ".screen .s-title{\n"
    "  top:calc(120px * var(--s));\n"
    "  font-size:calc(24px * var(--s)); line-height:calc(22px * var(--s));\n"
    "}\n"
    "/* 真机: 大数字 TOP_MID y=158，36px 像素数字 */\n"
    ".screen .s-big{\n"
    "  top:calc(158px * var(--s));\n"
    "  font-size:calc(36px * var(--s)); line-height:calc(33px * var(--s));\n"
    "}\n"
    "/* 真机: 单位 TOP_MID y=196，12px */\n"
    ".screen .s-unit{top:calc(196px * var(--s)); font-size:calc(12px * var(--s)); line-height:calc(11px * var(--s))}\n"
    ".screen .s-date{top:calc(228px * var(--s)); font-size:calc(12px * var(--s)); line-height:calc(11px * var(--s))}\n"
    ".screen .s-hint{\n"
    "  bottom:calc(6px * var(--s)); font-size:calc(12px * var(--s)); line-height:calc(11px * var(--s));\n"
    "}\n"
    "/* 真机: 分隔线 (60,216,120,3)，颜色 COL_SHADOW */\n"
    ".screen .s-divider{\n"
    "  position:absolute; width:calc(120px * var(--s)); height:calc(3px * var(--s));\n"
    "  left:calc(60px * var(--s)); top:calc(216px * var(--s)); background:var(--shadow);\n"
    "}\n"
    "/* 事件卡：页码 TOP_LEFT(12,8) 12px；图标 40² TOP_MID y=40；名称 y=92 24px；\n"
    "   大数字 y=130 36px；单位 y=172 12px；日期 y=194 12px —— 与 love_app.c 一致。 */\n"
    ".screen .s-page{\n"
    "  left:calc(12px * var(--s)); right:auto; text-align:left; top:calc(8px * var(--s));\n"
    "  font-size:calc(12px * var(--s)); line-height:calc(11px * var(--s));\n"
    "}\n"
    ".screen .s-event-icon{top:calc(40px * var(--s))}\n"
    ".screen .s-event-icon img{\n"
    "  width:calc(40px * var(--s)); height:calc(40px * var(--s));\n"
    "  image-rendering:pixelated; display:block; margin:0 auto;\n"
    "}\n"
    ".screen .s-event-name{top:calc(92px * var(--s)); font-size:calc(24px * var(--s)); line-height:calc(22px * var(--s))}\n"
    ".screen .s-event-big{top:calc(130px * var(--s)); font-size:calc(36px * var(--s)); line-height:calc(33px * var(--s))}\n"
    ".screen .s-event-unit{top:calc(172px * var(--s)); font-size:calc(12px * var(--s)); line-height:calc(11px * var(--s))}\n"
    ".screen .s-event-date{top:calc(194px * var(--s)); font-size:calc(12px * var(--s)); line-height:calc(11px * var(--s))}\n"
    ".pill{\n"
    "  display:inline-block; font-size:11px; padding:2px 8px; border:2px solid var(--ink);\n"
    "  background:var(--yellow);\n"
    "}\n"
    ".pill.ok{background:#B7F08B}\n"
    ".pill.warn{background:#FFC0C4}\n";
#define LOVE_ADMIN_CSS_SIZE (sizeof(LOVE_ADMIN_CSS) - 1)

static const char LOVE_ADMIN_JS[] =
    "// assets/web/admin.js —— 后台网页脚本,由设备以 /admin.js 单独返回。\n"
    "// 图标是内联的 data URI(一共两千多字节)。不要改回 /icon/N.png 那种独立资源:\n"
    "// 一次页面加载会多出十六个并发请求,把设备那点堆压到 Wi-Fi 驱动发不出帧。\n"
    "const ICONS = [{\"label\": \"小鸟\", \"data\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAaUlEQVR42u3YsQnAIBAFULdImzJkiAydbTKNDqCkMAdqeB9+KT4LES8lEYnJtp+5t4CAvwO2NsnP0d1wNCDgKsAvB2muva+qgIBLA6NvNiAgYNTzBwg4GhiNnv4jBQg4etow/UgOEPAlBdFRZ1bzlGHgAAAAAElFTkSuQmCC\"}, {\"label\": \"猫咪\", \"data\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAdUlEQVR42u3YsQ3AIAxEUbagpc7QHpCaPhkgSDnJhsTRR7oS/BojcKntOJWU4CXXBQjwi0Azk6IW8ZwHEGBqYHQAAkwNjO5OgAB/B+SaAQjwAThGv0V9D872AgSYBqj++rd0rGcsARDgTqBnXPbWOA8gwFXAC+8keDJvxXjhAAAAAElFTkSuQmCC\"}, {\"label\": \"狗狗\", \"data\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAdklEQVR42u3YsQnAIBBGYbdImzqt22SkTOQqmSRl7EXIwX+YO3jCq++zEbyy7cc7Vn46UwtAgBGBs66zumadCxBgSKA3RkEDBJgGqFxEmQEQYBogzwxAg"
    "B/A526uAQSYBmj94StoCQMQYESgFa20ZHcHEKADsAPFN+lyuT26YAAAAABJRU5ErkJggg==\"}, {\"label\": \"兔子\", \"data\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAXklEQVR42u3UsQ3AIAwEQG+RNnX2nyo1fRggFJZAUYB76UvbVzmikeO8nkwjmdH7AAF/CSzlfjV7ODsLCLgcsKeAgFsAvRlAQG8GEDA+QQ/HAALOAuwpIOByQJFdUwHURix3up3JeQAAAABJRU5ErkJggg==\"}, {\"label\": \"小熊\", \"data\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAc0lEQVR42u3YsQ3AIAxEUbZIm5o222SkTMQqTEJJVjhhQ2L0ka7FrzESl44zdyXJ+chzAQL8I/C5LynqEMt9AAGGBnoHIMDQQO/tBAhwOyDPDECAA8BWixSAAEMD1V//ko211BIAAa4EWuqyr+o8gABnAV9PMJ4OXyQr3QAAAABJRU5ErkJggg==\"}, {\"label\": \"狐狸\", \"data\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAZ0lEQVR42u3YsQkAIAxEUbewtXYIh3ZB7dVCOElUfuDqvDSBJMSU25jgVEsLQIA3Alst"
    "U5RBpB4AAb4CtAhAgE8DlUHc1gxAgJbA4wUQIECAAD8BKkeOCQYgwBuBu2glJr87gAAPADuld/9aCLpO8QAAAABJRU5ErkJggg==\"}, {\"label\": \"爱心\", \"data\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAZ0lEQVR42u3YsQ2AMAwEwGxBS02TAdh/E/aABSiMsJxEupe+i5wrE7cmIt+z7ccd6ah5gIClwLeD19lDjV78Zx4g4NLA7AICAgICrgjMfoKlYwABZwRW/F1Ktg2AgJXAkpUGIOCEwAfO+VyYbMuHIAAAAABJRU5ErkJggg==\"}, {\"label\": \"星星\", \"data\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAb0lEQVR42u3YsQ0AIAhEUbawtTTuv4zT6AIWl4BI8UmoeRZ6QTNHtT630varAALMBN4G7zWkTkEDBPgKqN7EaKD8AgAEWBGoDo5ugABLAqNj7Vv8AQQIECDA4qnhObFrBkCAFYEZXxXhWx1AgI+AB+w9E5SXMnoMAAAAAElFTkSuQmCC\"}, {\"label\": \"小花\", \"data\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAdUlEQVR42u3VsQmAQBBE0e3CSLhQ7MfKxMz"
    "GLMMKzlwNBnZvPeEPTLYDL1szMUOZ673nukt921p0AALMBHowKWiAADOBKqYeU2hlNECAAAEC7BzILwYIMAi4bOOj6p26BQjwN0APOgUDEGCPQBX9GQYgwEbACwdg4XDRki0yAAAAAElFTkSuQmCC\"}, {\"label\": \"月亮\", \"data\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAWUlEQVR42u3YwQnAMAgAQLfIt8/S/ZfpNMkC+SkSwgl+5RBENCIR4/lmZUZ1AAJ2AncF5/+WZgoNCNgJ1C1AwGbg8WsNEBAQEND9AQhocAABrxkc/0HA24ALFsgf4pAITlwAAAAASUVORK5CYII=\"}, {\"label\": \"蛋糕\", \"data\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAcUlEQVR42u3TsQ2AMAwFUW9BS80QLEnLFIxFh5Te9MFFJEc4hvvSdVH0Gos4pseqdTLSAAKM3jQvWgcQ4G+BFsYTQICpgdaHvedCAwQ4IrCU85G11ncAAX4O+EYAAaYGXtveNYAA0wCjLrb5sgECDO4Gsifxnpk3Y7kAAAAASUVORK5CYII=\"}, {\"label\": \"礼物\", \"data\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAZU"
    "lEQVR42u3XIQ6AMBAEwP4CiyQYHsD/H1HPP4omqdgEQk7MJesu2zEn2tpklnUfSVo4X/cBAv4KnC1e5xElffhNHyBgSWClAAKWBI6+RUmvM+0DBAQEBAQEBAQEBAT0qwMEfOYGGtetUv6F5eIAAAAASUVORK5CYII=\"}, {\"label\": \"气球\", \"data\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAYElEQVR42u3YsQ2AMAwEQG+RlpqGAdh/E/aABShQ4lhEupe+ta60HfExbdvvzEZ2AAErgW8Dr/NI7RAaELASWIEZQgMCAgICAgICrg20sAICTjzmvT4AATvQ8acAAibkAQWoZRtawl5aAAAAAElFTkSuQmCC\"}, {\"label\": \"戒指\", \"data\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAdElEQVR42u3YsQnAMAxEUW3hNmXw/k1GyRwZQFlAhYKMzoEvuM6gV/mMzQozjumZmGoAAuwERouvx1NpQQMECBAgwI2A2QpbHYAAtwRGB/0+JQnRAAH+BVi5Fko7AAJUA1XtsryLAQLsBHa8EWV/gQABfgS+5d4qtTSeIkwAAAAASUVORK5CYII=\"}, {\"label\": \"叶子\", \"data\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA"
    "CgAAAAoCAYAAACM/rhtAAAAZklEQVR42u3YsQkAIAxE0Wxhay24pIO5mq4gEk4PfiD1PdKEJEJQpbZ12wEQoDPwNGTMftQAAdoAs4PTpwUQoBKYHSyZFkCAzkDJPgUI0AUoucIAAnQBfvWWAAjwx9dYvCqAAB8DN/PKGa8HWuB9AAAAAElFTkSuQmCC\"}, {\"label\": \"圣诞树\", \"data\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAgUlEQVR42u3YMQqAMAyF4dzC1VEEcXD0Jh7H0UN5D3fvUffaQUxIo/wP3lboNzWkIoqko0t5JVIAAvRM0/YpbwlYOgcQ4O+ApUvWfXhdczRAgJ5ADeacx1vN0QABRgTWKkCAnwFqxlqoZwYgQCYJQIAOQM3usi3To1b7bQAI0AB4AdZwR5m35ci9AAAAAElFTkSuQmCC\"}];\n"
    "// 设备端 4bpp 自定义头像用的 16 色调色板,顺序即索引顺序,必须与设备一致。\n"
    "const PALETTE = [[23, 32, 42], [255, 255, 255], [244, 244, 234], [228, 59, 47], [241, 147, 156], [247, 191, 196], [138, 90, 51], [247, 217, 184], [255, 178, 62], [255, 217, 40], [130, 190, 45], [85, 149, 29], [22, 137, 232], [185, 243, 255], [117, 87, 217], [158, 158, 158]];\n"
    "const AVA = 40;                       // 与设备端 LOVE_ICON_PX 一致\n"
    "const AVATAR_BYTES = AVA * AVA / 2;   // 40x40 4bpp = 800 字节\n"
    "const AVATAR_MAX = 4;\n"
    "const TRANSPARENT_PX = \"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7\";\n"
    "\n"
    "const byId = (id) => document.getElementById(id);\n"
    "\n"
    "// 设备回传的自定义头像(4bpp base64,每个槽位一个,空串表示没上传)\n"
    "let AVATARS = new Array(AVATAR_MAX).fill(\"\");\n"
    "\n"
    "let model = { start:\"\", blankOff:30, people:[{name:\"\",icon:0},{name:\"\",icon:1}], events:[] };\n"
    "\n"
    "function toast(msg){ const t = byId(\"toast\"); t.textContent = msg; t.classList.add(\"show\");\n"
    "  clearTimeout(t._h); t._h = setTimeout(()=>t.classList.remove(\"show\"), 2200); }\n"
    "\n"
    "async function api(path, options){\n"
    "  const res = await fetch(path, Object.assign({headers:{\"Content-Type\":\"application/json\"}}, options));\n"
    "  if(!res.ok) throw new Error(await res.text() || res.statusText);\n"
    "  return res.headers.get(\"Content-Type\")?.includes(\"json\") ? res.json() : res.text();\n"
    "}\n"
    "\n"
    "/* ---------- 自定义头像：网页压缩 -> 设备存 4bpp ---------- */\n"
    "\n"
    "// 在设备那张 16 色调色板里找最接近的颜色(欧氏距离)。像素风素材本来就只有这 16 色,\n"
    "// 所以量化后观感一致;照片会退化成这 16 色的网点图,这正是\"像素头像\"要的效果。\n"
    "function nearestPaletteIndex(r, g, b){\n"
    "  let best = 0, bestD = Infinity;\n"
    "  for(let i = 0; i < PALETTE.length; i++){\n"
    "    const p = PALETTE[i];\n"
    "    const d = (r - p[0]) ** 2 + (g - p[1]) ** 2 + (b - p[2]) ** 2;\n"
    "    if(d < bestD){ bestD = d; best = i; }\n"
    "  }\n"
    "  return best;\n"
    "}\n"
    "\n"
    "// 选中的图片 -> 40x40、量化到 16 色、打成 4bpp(每字节两个像素,高半字节在前)。\n"
    "// 先居中裁成正方形再缩放,避免把脸拉扁。\n"
    "//\n"
    "// 用 <img> 而不是 createImageBitmap 解码:iPhone 相册默认是 HEIC,Safari 的\n"
    "// createImageBitmap 对它的支持比 <img> 窄得多;走 <img> 就是走浏览器自己的\n"
    "// 图像管线,手机直接拍的照片也能选。解码失败时给一句人话,不要把原始异常抛到\n"
    "// toast 里。\n"
    "async function compressAvatar(file){\n"
    "  const url = URL.createObjectURL(file);\n"
    "  try {\n"
    "    const bitmap = await new Promise((resolve, reject) => {\n"
    "      const el = new Image();\n"
    "      el.onload = () => resolve(el);\n"
    "      el.onerror = () => reject(new Error(\"浏览器解不开这张图片，试试转成 PNG 或 JPEG\"));\n"
    "      el.src = url;\n"
    "    });\n"
    "\n"
    "    const w = bitmap.naturalWidth, h = bitmap.naturalHeight;\n"
    "    const side = Math.min(w, h);\n"
    "    const canvas = document.createElement(\"canvas\");\n"
    "    canvas.width = AVA; canvas.height = AVA;\n"
    "    const ctx = canvas.getContext(\"2d\", { willReadFrequently: true });\n"
    "    ctx.drawImage(bitmap, (w - side) / 2, (h - side) / 2, side, side, 0, 0, AVA, AVA);\n"
    "    const px = ctx.getImageData(0, 0, AVA, AVA).data;\n"
    "\n"
    "    const out = new Uint8Array(AVATAR_BYTES);\n"
    "    for(let i = 0; i < AVA * AVA; i++){\n"
    "      // 近乎透明的像素直接给白色(索引 1 = W),免得压出脏边\n"
    "      const idx = px[i*4 + 3] >= 128\n"
    "        ? nearestPaletteIndex(px[i*4], px[i*4 + 1], px[i*4 + 2])\n"
    "        : 1;\n"
    "      if(i % 2 === 0) out[i >> 1] = idx << 4;\n"
    "      else out[i >> 1] |= idx;\n"
    "    }\n"
    "    return out;\n"
    "  } finally {\n"
    "    URL.revokeObjectURL(url);\n"
    "  }\n"
    "}\n"
    "\n"
    "// 设备回传的 4bpp base64 -> 可直接显示的 data URI(选择器里的缩略图)\n"
    "function avatarThumb(base64){\n"
    "  if(!base64) return TRANSPARENT_PX;\n"
    "  const bin = atob(base64);\n"
    "  if(bin.length < AVATAR_BYTES) return TRANSPARENT_PX;\n"
    "\n"
    "  const canvas = document.createElement(\"canvas\");\n"
    "  canvas.width = AVA; canvas.height = AVA;\n"
    "  const ctx = canvas.getContext(\"2d\");\n"
    "  const img = ctx.createImageData(AVA, AVA);\n"
    "  for(let i = 0; i < AVA * AVA; i++){\n"
    "    const byte = bin.charCodeAt(i >> 1);\n"
    "    const idx = (i % 2 === 0) ? (byte >> 4) : (byte & 0x0F);\n"
    "    const p = PALETTE[idx] || [0, 0, 0];\n"
    "    img.data[i*4] = p[0]; img.data[i*4 + 1] = p[1]; img.data[i*4 + 2] = p[2];\n"
    "    img.data[i*4 + 3] = 255;\n"
    "  }\n"
    "  ctx.putImageData(img, 0, 0);\n"
    "  return canvas.toDataURL(\"image/png\");\n"
    "}\n"
    "\n"
    "// 图标号 -> 图片地址。0..15 是内置素材(/icon/NN.png),16..19 是自定义头像槽位。\n"
    "// 槽位还没上传数据时回落到第 0 个内置图标 —— 与设备端 resolve_icon() 的行为一致,\n"
    "// 否则预览会显示成一个空白头像,和真机对不上。\n"
    "function iconSrc(idx){\n"
    "  if(idx < ICONS.length) return ICONS[idx].data;\n"
    "  const data = AVATARS[idx - ICONS.length];\n"
    "  return data ? avatarThumb(data) : ICONS[0].data;\n"
    "}\n"
    "\n"
    "function iconLabel(idx){\n"
    "  return idx < ICONS.length ? ICONS[idx].label : `自定义 ${idx - ICONS.length + 1}`;\n"
    "}\n"
    "\n"
    "// 只有自定义头像(照片,满幅方角)加圆角。内置图标是透明背景的图形,给它加圆角\n"
    "// 会切到描边(实测 8 个图标的四角各有描边,合计 48 个像素),而设备端刻意不做这件事\n"
    "// —— 两端必须一致,否则网页预览会显示成设备上没有的样子。\n"
    "function setAvatarImg(el, idx){\n"
    "  el.src = iconSrc(idx);\n"
    "  el.classList.toggle(\"rounded\", idx >= ICONS.length);\n"
    "}\n"
    "\n"
    "async function uploadAvatar(slot, file){\n"
    "  const bytes = await compressAvatar(file);\n"
    "  const res = await fetch(`/api/avatar?slot=${slot}`, {\n"
    "    method: \"POST\",\n"
    "    headers: { \"Content-Type\": \"application/octet-stream\" },\n"
    "    body: bytes,\n"
    "  });\n"
    "  if(!res.ok){\n"
    "    const text = await res.text().catch(()=> \"\");\n"
    "    throw new Error(text || res.statusText);\n"
    "  }\n"
    "  return res.json();\n"
    "}\n"
    "\n"
    "async function clearAvatar(slot){\n"
    "  const res = await fetch(`/api/avatar/clear?slot=${slot}`, { method: \"POST\", body: \"{}\" });\n"
    "  if(!res.ok) throw new Error(res.statusText);\n"
    "  return res.json();\n"
    "}\n"
    "\n"
    "// 常驻一个已挂进文档的隐藏文件选择器。\n"
    "// 不要像早先那样每次现造一个游离的 input 再 click():iOS Safari 会忽略对\n"
    "// 未挂载元素的 click(),表现就是\"第一次点了没反应,要再点一次\"。\n"
    "const avatarInput = document.createElement(\"input\");\n"
    "avatarInput.type = \"file\";\n"
    "avatarInput.accept = \"image/*\";\n"
    "avatarInput.hidden = true;\n"
    "document.body.appendChild(avatarInput);\n"
    "\n"
    "// 触发文件选择 -> 压缩 -> 上传。成功后把该槽位设为当前选中图标。\n"
    "function pickAvatarFile(onDone){\n"
    "  // 先清空,否则连续两次选同一个文件不会触发 change\n"
    "  avatarInput.value = \"\";\n"
    "  avatarInput.onchange = async () => {\n"
    "    const file = avatarInput.files && avatarInput.files[0];\n"
    "    if(!file) return;\n"
    "    try{\n"
    "      await onDone(file);\n"
    "    }catch(e){\n"
    "      toast(\"上传失败：\" + e.message);\n"
    "    }\n"
    "  };\n"
    "  avatarInput.click();\n"
    "}\n"
    "\n"
    "/* 与设备 love_date.c 一致的规则：目标是“下一次发生日”，在一起天数含当天。 */\n"
    "function daysBetween(a, b){\n"
    "  const ms = Date.UTC(b.y, b.m-1, b.d) - Date.UTC(a.y, a.m-1, a.d);\n"
    "  return Math.round(ms / 86400000);\n"
    "}\n"
    "function parseDate(text){\n"
    "  if(!text) return null;\n"
    "  const p = text.split(\"-\").map(Number);\n"
    "  if(p.length !== 3 || !p[0]) return null;\n"
    "  return {y:p[0], m:p[1], d:p[2]};\n"
    "}\n"
    "function todayFrom(epoch){\n"
    "  const d = new Date((epoch + 8*3600) * 1000);\n"
    "  return {y:d.getUTCFullYear(), m:d.getUTCMonth()+1, d:d.getUTCDate(),\n"
    "          hh:String(d.getUTCHours()).padStart(2,\"0\"), mm:String(d.getUTCMinutes()).padStart(2,\"0\")};\n"
    "}\n"
    "function daysInMonth(y,m){ return new Date(Date.UTC(y, m, 0)).getUTCDate(); }\n"
    "function nextOccurrence(today, month, day){\n"
    "  const clamp = (y)=>Math.min(day, daysInMonth(y, month));\n"
    "  let cand = {y:today.y, m:month, d:clamp(today.y)};\n"
    "  if(daysBetween(today, cand) >= 0) return cand;\n"
    "  return {y:today.y+1, m:month, d:clamp(today.y+1)};\n"
    "}\n"
    "\n"
    "function currentToday(){\n"
    "  return lastTime && lastTime.synced ? todayFrom(lastTime.epoch) : todayFrom(Math.floor(Date.now()/1000));\n"
    "}\n"
    "\n"
    "/* ---------- 农历(与设备端 love_lunar.c 同一张表、同一套算法) ---------- */\n"
    "\n"
    "// 不用浏览器的 Intl 中国农历：实测 18 个年份里有 2 个(2027、2030)与权威日期差 ±1 天，\n"
    "// 拿它当预览依据会出现\"网页说 02-07、设备说 02-06\"。这里直接用设备端那张表。\n"
    "const LUNAR = {\n"
    " \"baseYear\": 2018,\n"
    " \"baseMonth\": 2,\n"
    " \"baseDay\": 16,\n"
    " \"info\": [\n"
    "  \"0x0D4A0\",\n"
    "  \"0x0C950\",\n"
    "  \"0x0A9E4\",\n"
    "  \"0x05560\",\n"
    "  \"0x0AB50\",\n"
    "  \"0x0ADA2\",\n"
    "  \"0x06D20\",\n"
    "  \"0x07656\",\n"
    "  \"0x07250\",\n"
    "  \"0x064B0\",\n"
    "  \"0x06575\",\n"
    "  \"0x0CAB0\",\n"
    "  \"0x055A0\",\n"
    "  \"0x056E3\",\n"
    "  \"0x0B690\",\n"
    "  \"0x0F52B\",\n"
    "  \"0x0B520\",\n"
    "  \"0x0B250\",\n"
    "  \"0x1D0B6\",\n"
    "  \"0x0A4B0\",\n"
    "  \"0x04AB0\",\n"
    "  \"0x02BB5\",\n"
    "  \"0x05AD0\",\n"
    "  \"0x0B6A0\",\n"
    "  \"0x0DAA2\",\n"
    "  \"0x0D920\",\n"
    "  \"0x0EA57\",\n"
    "  \"0x0D250\",\n"
    "  \"0x0A550\",\n"
    "  \"0x1A4D5\",\n"
    "  \"0x04B60\",\n"
    "  \"0x05B50\",\n"
    "  \"0x16D23\"\n"
    " ]\n"
    "};\n"
    "const LUNAR_INFO = LUNAR.info.map((hex) => parseInt(hex, 16));\n"
    "const LUNAR_BASE = { y: LUNAR.baseYear, m: LUNAR.baseMonth, d: LUNAR.baseDay };\n"
    "\n"
    "const dayNumber = (y, m, d) => Math.round(Date.UTC(y, m - 1, d) / 86400000);\n"
    "const fromDayNumber = (n) => {\n"
    "  const dt = new Date(n * 86400000);\n"
    "  return { y: dt.getUTCFullYear(), m: dt.getUTCMonth() + 1, d: dt.getUTCDate() };\n"
    "};\n"
    "const lunarInRange = (y) => y >= LUNAR.baseYear && y < LUNAR.baseYear + LUNAR_INFO.length;\n"
    "\n"
    "function lunarLeapMonth(y){\n"
    "  return lunarInRange(y) ? (LUNAR_INFO[y - LUNAR.baseYear] & 0x0F) : 0;\n"
    "}\n"
    "function lunarPlainMonthDays(y, m){\n"
    "  return (LUNAR_INFO[y - LUNAR.baseYear] & (1 << (4 + m - 1))) ? 30 : 29;\n"
    "}\n"
    "function lunarLeapDays(y){\n"
    "  return (LUNAR_INFO[y - LUNAR.baseYear] & (1 << 16)) ? 30 : 29;\n"
    "}\n"
    "function lunarYearDays(y){\n"
    "  let days = 0;\n"
    "  for(let m = 1; m <= 12; m++) days += lunarPlainMonthDays(y, m);\n"
    "  const leap = lunarLeapMonth(y);\n"
    "  if(leap) days += lunarLeapDays(y);\n"
    "  return days;\n"
    "}\n"
    "\n"
    "// 农历 (year, month, day) -> 公历；day = 0 表示该月最后一天(除夕那种)。\n"
    "function lunarToSolar(ly, lm, ld){\n"
    "  if(!lunarInRange(ly) || lm < 1 || lm > 12) return null;\n"
    "\n"
    "  const leap = lunarLeapMonth(ly);\n"
    "  let offset = 0;\n"
    "  for(let m = 1; m < lm; m++){\n"
    "    offset += lunarPlainMonthDays(ly, m);\n"
    "    if(leap === m) offset += lunarLeapDays(ly);   // 闰月排在其月之后\n"
    "  }\n"
    "  const length = lunarPlainMonthDays(ly, lm);\n"
    "  const day = (ld === 0) ? length : ld;\n"
    "  if(day < 1 || day > length) return null;\n"
    "\n"
    "  let before = 0;\n"
    "  for(let y = LUNAR.baseYear; y < ly; y++) before += lunarYearDays(y);\n"
    "  return fromDayNumber(dayNumber(LUNAR_BASE.y, LUNAR_BASE.m, LUNAR_BASE.d)\n"
    "                       + before + offset + day - 1);\n"
    "}\n"
    "\n"
    "// 农历月日在 today 当天或之后的下一次发生日(含今天)。\n"
    "function nextLunar(today, lm, ld){\n"
    "  const from = dayNumber(today.y, today.m, today.d);\n"
    "  let best = null;\n"
    "  for(let ly = today.y - 1; ly <= today.y + 1; ly++){\n"
    "    const c = lunarToSolar(ly, lm, ld);\n"
    "    if(!c) continue;\n"
    "    const n = dayNumber(c.y, c.m, c.d);\n"
    "    if(n < from) continue;\n"
    "    if(!best || n < best.n) best = { n, ...c };\n"
    "  }\n"
    "  return best ? { y: best.y, m: best.m, d: best.d } : null;\n"
    "}\n"
    "\n"
    "const LUNAR_MONTHS = [\"\", \"正月\",\"二月\",\"三月\",\"四月\",\"五月\",\"六月\",\n"
    "                      \"七月\",\"八月\",\"九月\",\"十月\",\"冬月\",\"腊月\"];\n"
    "\n"
    "// 与设备端 love_lunar_format 一致:初八 / 十五 / 廿二 / 三十 / 月末\n"
    "function lunarName(month, day){\n"
    "  if(month < 1 || month > 12) return \"农历\";\n"
    "  if(day === 0) return `${LUNAR_MONTHS[month]}最后一天`;\n"
    "  const TENS = [\"初\", \"十\", \"廿\", \"三\"], UNITS = [\"十\",\"一\",\"二\",\"三\",\"四\",\"五\",\"六\",\"七\",\"八\",\"九\"];\n"
    "  let dayName;\n"
    "  if(day === 10) dayName = \"初十\";\n"
    "  else if(day === 20) dayName = \"二十\";\n"
    "  else if(day === 30) dayName = \"三十\";\n"
    "  else dayName = TENS[Math.floor(day / 10)] + UNITS[day % 10];\n"
    "  return LUNAR_MONTHS[month] + dayName;\n"
    "}\n"
    "\n"
    "function renderPreview(){\n"
    "  const today = currentToday();\n"
    "  const start = parseDate(model.start);\n"
    "  byId(\"pvDays\").textContent = start ? (daysBetween(start, today) + 1) : \"--\";\n"
    "  byId(\"pvStart\").textContent = \"起始日 \" + (model.start || \"----\");\n"
    "  // 设备主屏不再显示对时时间,只用单位那行标注时间状态。\n"
    "  // 提示:设备侧还可能拿断电前的天数快照顶上,那种情况显示\"天(未对时)\",这里判断不到。\n"
    "  byId(\"pvUnit\").textContent = lastTime && lastTime.synced ? \"天\" : \"天(未对时)\";\n"
    "  const soc = typeof lastBattery === \"number\" && lastBattery >= 0 ? lastBattery : null;\n"
    "  byId(\"pvBattery\").textContent = soc === null ? \"-- %\" : soc + \"%\";\n"
    "  byId(\"pvBatFill\").style.width = (soc === null ? 0 : soc) + \"%\";\n"
    "  setAvatarImg(byId(\"pvIconA\"), model.people[0].icon);\n"
    "  setAvatarImg(byId(\"pvIconB\"), model.people[1].icon);\n"
    "  byId(\"pvNameA\").textContent = model.people[0].name || \"TA\";\n"
    "  byId(\"pvNameB\").textContent = model.people[1].name || \"TA\";\n"
    "\n"
    "  const e = model.events[0];\n"
    "  if(e){\n"
    "    const synced = !!(lastTime && lastTime.synced);\n"
    "    let target = null;\n"
    "    let dateLine = \"目标日 ----\";\n"
    "\n"
    "    if(e.kind === 2){\n"
    "      // 农历:按农历月日找下一次;折算不出公历就只报农历,不给假日期\n"
    "      const lname = lunarName(e.lunarMonth, e.lunarDay);\n"
    "      target = nextLunar(today, e.lunarMonth, e.lunarDay);\n"
    "      dateLine = target\n"
    "        ? `农历${lname} ${target.y}-${String(target.m).padStart(2,\"0\")}-${String(target.d).padStart(2,\"0\")}`\n"
    "        : `农历${lname}`;\n"
    "    } else {\n"
    "      const d = parseDate(e.date);\n"
    "      target = e.kind === 0 ? nextOccurrence(today, d.m, d.d) : d;\n"
    "      dateLine = \"目标日 \" + target.y + \"-\" +\n"
    "        String(target.m).padStart(2,\"0\") + \"-\" + String(target.d).padStart(2,\"0\");\n"
    "    }\n"
    "\n"
    "    const diff = target ? daysBetween(today, target) : 0;\n"
    "    byId(\"pvEventName\").textContent = e.name || \"纪念日\";\n"
    "    byId(\"pvEventDays\").textContent = (synced && target) ? Math.abs(diff) : \"--\";\n"
    "    byId(\"pvEventUnit\").textContent = !synced ? \"未同步\"\n"
    "                                      : (!target ? \"农历超出范围\" : (diff >= 0 ? \"天后\" : \"天前\"));\n"
    "    byId(\"pvEventDate\").textContent = dateLine;\n"
    "    setAvatarImg(byId(\"pvEventIcon\"), e.icon);\n"
    "  }\n"
    "  byId(\"eventCount\").textContent = model.events.length ? `共 ${model.events.length} 条` : \"还没有事件\";\n"
    "  updatePreviewHint();\n"
    "}\n"
    "\n"
    "// 底部提示行要跟真机一致:农历事件的卡片提示不同,列表模式下主屏的上/下是\"进列表\"。\n"
    "// 单独成函数是因为它同时依赖\"当前预览哪个屏\"和\"展示模式\",两边都要能触发刷新。\n"
    "function updatePreviewHint(){\n"
    "  const main = byId(\"pvMainView\").style.display !== \"none\";\n"
    "  // 设备上事件卡不再能改日期,所以卡片提示只说怎么走;主屏提示看有没有\"列表\"事件。\n"
    "  const hasList = model.events.some((e) => (e.viewMode ?? 0) === 0);\n"
    "  byId(\"pvHint\").textContent = main\n"
    "    ? (hasList ? \"上/下 列表 · 长按确定 设置\" : \"上/下 切换 · 长按确定 设置\")\n"
    "    : \"上/下 翻卡 · 长按确定 设置\";\n"
    "}\n"
    "\n"
    "// 切换预览视图时，页码与底部提示行也要跟真机一致。\n"
    "function showPreviewView(which){\n"
    "  const main = which === \"main\";\n"
    "  byId(\"pvMainView\").style.display = main ? \"\" : \"none\";\n"
    "  byId(\"pvEventView\").style.display = main ? \"none\" : \"\";\n"
    "  byId(\"pvEventPage\").style.display = main ? \"none\" : \"\";\n"
    "  byId(\"pvEventPage\").textContent = \"1/\" + model.events.length;\n"
    "  updatePreviewHint();\n"
    "}\n"
    "\n"
    "function iconPicker(container, onPick, selected, onAvatarChanged){\n"
    "  container.innerHTML = \"\";\n"
    "  const total = ICONS.length + AVATAR_MAX;\n"
    "\n"
    "  for(let i = 0; i < total; i++){\n"
    "    const custom = i >= ICONS.length;\n"
    "    const slot = i - ICONS.length;\n"
    "    const uploaded = custom && !!AVATARS[slot];\n"
    "\n"
    "    const btn = document.createElement(\"button\");\n"
    "    btn.type = \"button\";\n"
    "    btn.className = (i === selected) ? \"sel\" : \"\";\n"
    "    if(custom && !uploaded) btn.classList.add(\"empty\");\n"
    "    btn.title = iconLabel(i);\n"
    "    btn.innerHTML = (custom && !uploaded)\n"
    "      ? '<span class=\"plus\">＋</span>'\n"
    "      : `<img class=\"${custom ? \"rounded\" : \"\"}\" src=\"${custom ? avatarThumb(AVATARS[slot]) : ICONS[i].data}\" alt=\"\">`;\n"
    "    btn.onclick = () => {\n"
    "      // 空的自定义槽位：点一下直接选图，省掉\"先选中再上传\"的两步\n"
    "      if(custom && !uploaded){\n"
    "        pickAvatarFile(async (file) => {\n"
    "          await uploadAvatar(slot, file);\n"
    "          onPick(i);\n"
    "          if(onAvatarChanged) await onAvatarChanged();\n"
    "          toast(\"头像已存入设备\");\n"
    "        });\n"
    "        return;\n"
    "      }\n"
    "      onPick(i);\n"
    "    };\n"
    "    container.appendChild(btn);\n"
    "  }\n"
    "\n"
    "  // 选中自定义槽位时补一条操作栏（占满整行，不参与 8 列网格）\n"
    "  if(selected >= ICONS.length){\n"
    "    const slot = selected - ICONS.length;\n"
    "    const bar = document.createElement(\"div\");\n"
    "    bar.className = \"avabar\";\n"
    "    bar.innerHTML =\n"
    "      `<button type=\"button\" class=\"ghost\" data-act=\"up\">${AVATARS[slot] ? \"替换图片\" : \"上传图片\"}</button>`\n"
    "      + (AVATARS[slot] ? '<button type=\"button\" class=\"ghost\" data-act=\"clear\">清除</button>' : \"\")\n"
    "      + '<span class=\"muted\">会压成 40×40、量化到设备那 16 色后存进去</span>';\n"
    "\n"
    "    bar.querySelector('[data-act=\"up\"]').onclick = () => pickAvatarFile(async (file) => {\n"
    "      await uploadAvatar(slot, file);\n"
    "      onPick(selected);\n"
    "      if(onAvatarChanged) await onAvatarChanged();\n"
    "      toast(\"头像已存入设备\");\n"
    "    });\n"
    "\n"
    "    const clearBtn = bar.querySelector('[data-act=\"clear\"]');\n"
    "    if(clearBtn) clearBtn.onclick = async () => {\n"
    "      try{\n"
    "        await clearAvatar(slot);\n"
    "        onPick(0);\n"
    "        if(onAvatarChanged) await onAvatarChanged();\n"
    "        toast(\"已清除，退回内置图标\");\n"
    "      }catch(e){ toast(\"清除失败：\" + e.message); }\n"
    "    };\n"
    "\n"
    "    container.appendChild(bar);\n"
    "  }\n"
    "}\n"
    "\n"
    "function renderAll(){\n"
    "  byId(\"start\").value = model.start;\n"
    "  byId(\"blankOff\").value = String(model.blankOff ?? 30);\n"
    "  byId(\"bleEnabled\").value = model.bleEnabled ? \"1\" : \"0\";\n"
    "  byId(\"nameA\").value = model.people[0].name;\n"
    "  byId(\"nameB\").value = model.people[1].name;\n"
    "  iconPicker(byId(\"iconsA\"), (i)=>{ model.people[0].icon = i; renderAll(); },\n"
    "             model.people[0].icon, refreshAvatars);\n"
    "  iconPicker(byId(\"iconsB\"), (i)=>{ model.people[1].icon = i; renderAll(); },\n"
    "             model.people[1].icon, refreshAvatars);\n"
    "  renderEvents();\n"
    "  renderPreview();\n"
    "}\n"
    "\n"
    "const openIcon = new Set();   // 头像选择器处于展开状态的事件下标\n"
    "const collapsed = new Set();  // 处于\"收起\"状态的事件卡下标\n"
    "\n"
    "// 把用户填的文本放进 HTML 属性/文本里。名字与分类都是用户自由输入的,\n"
    "// 里面带个引号或尖括号就会把这段模板撑坏。\n"
    "const esc = (s) => String(s ?? \"\").replace(/[&<>\"]/g,\n"
    "  (c) => ({ \"&\":\"&amp;\", \"<\":\"&lt;\", \">\":\"&gt;\", '\"':\"&quot;\" }[c]));\n"
    "\n"
    "// 用户填过的分类名(去重、按首次出现排序),给分类输入框的 datalist 用 ——\n"
    "// 少手打一遍就少一次把\"生日\"写成\"生日 \"那样的错。\n"
    "function usedCategories(){\n"
    "  const seen = [];\n"
    "  model.events.forEach((e) => {\n"
    "    const c = (e.category || \"\").trim();\n"
    "    if(c && !seen.includes(c)) seen.push(c);\n"
    "  });\n"
    "  return seen;\n"
    "}\n"
    "\n"
    "function updateCategoryOptions(){\n"
    "  const list = byId(\"categoryOptions\");\n"
    "  if(!list) return;\n"
    "  list.innerHTML = usedCategories().map((c) => `<option value=\"${esc(c)}\"></option>`).join(\"\");\n"
    "}\n"
    "\n"
    "// 上移/下移只改持久顺序(设备端的显示分组顺序由它决定),不改任何事件的内容。\n"
    "function moveEvent(idx, delta){\n"
    "  const to = idx + delta;\n"
    "  if(to < 0 || to >= model.events.length) return;\n"
    "  const [moved] = model.events.splice(idx, 1);\n"
    "  model.events.splice(to, 0, moved);\n"
    "  remapIndexSets(idx, to);\n"
    "  renderEvents(); renderPreview();\n"
    "}\n"
    "\n"
    "// 两条事件换位后,把\"按下标记录\"的两套界面状态跟着搬过去。\n"
    "// 不搬的话,收起/展开的会是换位之后的另一条,看起来像随机跳动。\n"
    "function remapIndexSets(from, to){\n"
    "  [openIcon, collapsed].forEach((set) => {\n"
    "    const hadFrom = set.has(from);\n"
    "    const hadTo = set.has(to);\n"
    "    set.delete(from);\n"
    "    set.delete(to);\n"
    "    if(hadTo) set.add(from);\n"
    "    if(hadFrom) set.add(to);\n"
    "  });\n"
    "}\n"
    "\n"
    "function renderEvents(){\n"
    "  const host = byId(\"events\");\n"
    "  host.innerHTML = \"\";\n"
    "  updateCategoryOptions();\n"
    "  if(!model.events.length){\n"
    "    openIcon.clear();\n"
    "    collapsed.clear();\n"
    "    host.innerHTML = '<p class=\"muted\">还没有事件，点下面的按钮添加。</p>';\n"
    "    return;\n"
    "  }\n"
    "  model.events.forEach((e, idx) => {\n"
    "    const open = openIcon.has(idx);\n"
    "    const isCollapsed = collapsed.has(idx);\n"
    "    const iconLabelText = iconLabel(e.icon);\n"
    "    const iconSrcText = iconSrc(e.icon);\n"
    "    const isLunar = e.kind === 2;\n"
    "    const lunarMonth = e.lunarMonth ?? 1;\n"
    "    const lunarDay = e.lunarDay ?? 1;\n"
    "\n"
    "    const monthOpts = Array.from({length: 12}, (_, i) =>\n"
    "      `<option value=\"${i+1}\"${(i+1) === lunarMonth ? \" selected\" : \"\"}>${LUNAR_MONTHS[i+1]}</option>`).join(\"\");\n"
    "    // 0 = 月末，专门留给除夕这类节日\n"
    "    const dayWords = [\"月末\", \"初一\",\"初二\",\"初三\",\"初四\",\"初五\",\"初六\",\"初七\",\"初八\",\"初九\",\"初十\",\n"
    "      \"十一\",\"十二\",\"十三\",\"十四\",\"十五\",\"十六\",\"十七\",\"十八\",\"十九\",\"二十\",\n"
    "      \"廿一\",\"廿二\",\"廿三\",\"廿四\",\"廿五\",\"廿六\",\"廿七\",\"廿八\",\"廿九\",\"三十\"];\n"
    "    const dayOpts = dayWords.map((w, i) =>\n"
    "      `<option value=\"${i}\"${i === lunarDay ? \" selected\" : \"\"}>${w}</option>`).join(\"\");\n"
    "\n"
    "    const box = document.createElement(\"div\");\n"
    "    box.className = \"event\";\n"
    "    // 标题上带上名字:收起之后仍要知道这是哪一条,不然只能靠逐条展开找。\n"
    "    box.innerHTML = `\n"
    "      <div class=\"head\">\n"
    "        <span>事件 ${idx+1}${e.name ? \" · \" + esc(e.name) : \"\"}${\n"
    "          e.viewMode === 1 ? ' <span class=\"muted\">单页</span>' : \"\"}</span>\n"
    "        <span class=\"headbtns\">\n"
    "          <button type=\"button\" class=\"ghost tile\" data-move=\"${idx}\" data-delta=\"-1\"\n"
    "                  title=\"上移\"${idx === 0 ? \" disabled\" : \"\"}>↑</button>\n"
    "          <button type=\"button\" class=\"ghost tile\" data-move=\"${idx}\" data-delta=\"1\"\n"
    "                  title=\"下移\"${idx === model.events.length - 1 ? \" disabled\" : \"\"}>↓</button>\n"
    "          <button type=\"button\" class=\"ghost\" data-collapse=\"${idx}\">${isCollapsed ? \"展开\" : \"收起\"}</button>\n"
    "          <button type=\"button\" class=\"ghost\" data-remove=\"${idx}\">删除</button>\n"
    "        </span>\n"
    "      </div>\n"
    "      <div class=\"body\"${isCollapsed ? \" hidden\" : \"\"}>\n"
    "      <label>名称</label><input type=\"text\" maxlength=\"8\" data-name=\"${idx}\" value=\"${esc(e.name)}\">\n"
    "      <label>分类 <span class=\"muted\">留空 = 不分类</span></label>\n"
    "      <input type=\"text\" maxlength=\"8\" list=\"categoryOptions\" data-category=\"${idx}\"\n"
    "             value=\"${esc(e.category)}\" placeholder=\"例如 生日、节日、家人\">\n"
    "      <label>展示</label>\n"
    "      <select data-view=\"${idx}\">\n"
    "        <option value=\"0\"${(e.viewMode ?? 0) === 0 ? \" selected\" : \"\"}>进列表（一屏 4 条，可按分类分组）</option>\n"
    "        <option value=\"1\"${e.viewMode === 1 ? \" selected\" : \"\"}>单页（自己独占一屏）</option>\n"
    "      </select>\n"
    "      <label>重复方式</label>\n"
    "      <select data-kind=\"${idx}\">\n"
    "        <option value=\"0\"${e.kind===0?\" selected\":\"\"}>每年重复（生日 / 节日）</option>\n"
    "        <option value=\"1\"${e.kind===1?\" selected\":\"\"}>仅一次（具体纪念日）</option>\n"
    "        <option value=\"2\"${isLunar?\" selected\":\"\"}>农历每年（春节 / 中秋）</option>\n"
    "      </select>\n"
    "      ${isLunar\n"
    "        ? `<label>农历日期 <span class=\"muted\">${lunarName(lunarMonth, lunarDay)}</span></label>\n"
    "           <div class=\"row\">\n"
    "             <select data-lmonth=\"${idx}\">${monthOpts}</select>\n"
    "             <select data-lday=\"${idx}\">${dayOpts}</select>\n"
    "           </div>\n"
    "           <p class=\"muted\">农历节日请选这项：设备会按农历折算到下一次的公历日期。选“月末”就是除夕那种。</p>`\n"
    "        : `<label>日期</label><input type=\"date\" data-date=\"${idx}\" value=\"${e.date}\">`}\n"
    "      <label>头像 <span class=\"muted\">${iconLabelText}</span></label>\n"
    "      <div class=\"iconrow\">\n"
    "        <button type=\"button\" class=\"iconcur\" data-toggle=\"${idx}\" title=\"更换头像\">\n"
    "          <img class=\"${e.icon >= ICONS.length ? \"rounded\" : \"\"}\" src=\"${iconSrcText}\" alt=\"${iconLabelText}\"></button>\n"
    "        <button type=\"button\" class=\"ghost\" data-toggle=\"${idx}\">${open ? \"收起\" : \"更换\"}</button>\n"
    "      </div>\n"
    "      <div class=\"icons\" data-icons=\"${idx}\"${open ? \"\" : \" hidden\"}></div>\n"
    "      </div>`;\n"
    "    host.appendChild(box);\n"
    "    iconPicker(box.querySelector(`[data-icons=\"${idx}\"]`),\n"
    "      (i)=>{ model.events[idx].icon = i; openIcon.delete(idx); renderEvents(); renderPreview(); },\n"
    "      e.icon, refreshAvatars);\n"
    "  });\n"
    "  host.querySelectorAll(\"[data-toggle]\").forEach(b => b.onclick = () => {\n"
    "    const i = Number(b.dataset.toggle);\n"
    "    if(openIcon.has(i)) openIcon.delete(i); else openIcon.add(i);\n"
    "    renderEvents();\n"
    "  });\n"
    "  host.querySelectorAll(\"[data-collapse]\").forEach(b => b.onclick = () => {\n"
    "    const i = Number(b.dataset.collapse);\n"
    "    if(collapsed.has(i)) collapsed.delete(i); else collapsed.add(i);\n"
    "    // 收起时把头像选择器也收掉,否则展开回来会发现它莫名其妙开着。\n"
    "    openIcon.delete(i);\n"
    "    renderEvents();\n"
    "  });\n"
    "  host.querySelectorAll(\"[data-move]\").forEach(b => b.onclick = () => {\n"
    "    moveEvent(Number(b.dataset.move), Number(b.dataset.delta));\n"
    "  });\n"
    "  host.querySelectorAll(\"[data-remove]\").forEach(b => b.onclick = () => {\n"
    "    const i = Number(b.dataset.remove);\n"
    "    model.events.splice(i, 1);\n"
    "    // 下标会整体前移,两套按下标记录的状态都不再有意义。\n"
    "    openIcon.clear();\n"
    "    collapsed.clear();\n"
    "    renderEvents(); renderPreview();\n"
    "  });\n"
    "  host.querySelectorAll(\"[data-name]\").forEach(i => i.oninput = () => {\n"
    "    model.events[Number(i.dataset.name)].name = i.value; renderPreview();\n"
    "  });\n"
    "  host.querySelectorAll(\"[data-category]\").forEach(i => i.oninput = () => {\n"
    "    model.events[Number(i.dataset.category)].category = i.value;\n"
    "    // 只刷 datalist,不重建列表 —— 重建会让正在输入的这个框失去焦点。\n"
    "    updateCategoryOptions();\n"
    "  });\n"
    "  host.querySelectorAll(\"[data-view]\").forEach(i => i.onchange = () => {\n"
    "    const idx = Number(i.dataset.view);\n"
    "    model.events[idx].viewMode = Number(i.value);\n"
    "    // 只刷预览的提示行,不重建整张列表 —— 重建会把刚操作的这一条挤走。\n"
    "    renderPreview();\n"
    "  });\n"
    "  host.querySelectorAll(\"[data-date]\").forEach(i => i.onchange = () => {\n"
    "    model.events[Number(i.dataset.date)].date = i.value; renderPreview();\n"
    "  });\n"
    "  host.querySelectorAll(\"[data-kind]\").forEach(i => i.onchange = () => {\n"
    "    const idx = Number(i.dataset.kind);\n"
    "    const e = model.events[idx];\n"
    "    e.kind = Number(i.value);\n"
    "    if(e.kind === 2){\n"
    "      // 切到农历时补默认值，并保证 date 字段不再被当成农历来源\n"
    "      if(e.lunarMonth == null) e.lunarMonth = 1;\n"
    "      if(e.lunarDay == null) e.lunarDay = 1;\n"
    "    }\n"
    "    // 日期控件会随 kind 换形态，必须整体重建\n"
    "    renderEvents(); renderPreview();\n"
    "  });\n"
    "  host.querySelectorAll(\"[data-lmonth]\").forEach(i => i.onchange = () => {\n"
    "    const e = model.events[Number(i.dataset.lmonth)];\n"
    "    e.lunarMonth = Number(i.value);\n"
    "    renderEvents(); renderPreview();\n"
    "  });\n"
    "  host.querySelectorAll(\"[data-lday]\").forEach(i => i.onchange = () => {\n"
    "    const e = model.events[Number(i.dataset.lday)];\n"
    "    e.lunarDay = Number(i.value);\n"
    "    renderEvents(); renderPreview();\n"
    "  });\n"
    "  byId(\"eventCount\").textContent = model.events.length ? `共 ${model.events.length} 条` : \"还没有事件\";\n"
    "}\n"
    "\n"
    "let lastTime = null;\n"
    "let lastBattery = null;\n"
    "function renderTimeAndNet(state){\n"
    "  lastTime = state.time;\n"
    "  lastBattery = typeof state.battery === \"number\" && state.battery >= 0 ? state.battery : null;\n"
    "  byId(\"timeText\").textContent = state.time.synced ? state.time.text : \"未同步\";\n"
    "  const pill = byId(\"timePill\");\n"
    "  pill.textContent = state.time.synced ? state.time.sourceText : \"等待对时\";\n"
    "  pill.className = \"pill \" + (state.time.synced ? \"ok\" : \"warn\");\n"
    "\n"
    "  const net = state.net;\n"
    "  const np = byId(\"netPill\");\n"
    "  np.textContent = net.stateText;\n"
    "  np.className = \"pill \" + (net.state === \"connected\" ? \"ok\" : (net.ap ? \"warn\" : \"\"));\n"
    "  byId(\"netIp\").textContent = net.ip || \"—\";\n"
    "  byId(\"netSsid\").textContent = net.ssid || \"尚未配置\";\n"
    "  byId(\"netUrl\").textContent = net.url || \"热点已关闭\";\n"
    "  // 热点空闲关闭后(默认 5 分钟无操作)只能从同一局域网访问,所以两个地址都要给。\n"
    "  byId(\"netLanUrl\").textContent = net.lanUrl || \"未联网\";\n"
    "  byId(\"apInfo\").textContent = net.ap ? `${net.apSsid} / 密码 ${net.apPass}` : \"已关闭\";\n"
    "  byId(\"deviceName\").textContent = state.deviceName;\n"
    "}\n"
    "\n"
    "async function load(){\n"
    "  const state = await api(\"/api/state\");\n"
    "  model = JSON.parse(JSON.stringify(state.config));\n"
    "  AVATARS = state.avatars || new Array(AVATAR_MAX).fill(\"\");\n"
    "  byId(\"deviceName\").textContent = state.deviceName;\n"
    "  // 先吃时间与电量，预览里的对时文案和右上角电量才不会先渲染成占位符。\n"
    "  renderTimeAndNet(state);\n"
    "  renderAll();\n"
    "}\n"
    "\n"
    "// 只刷自定义头像(不碰 model，免得把用户没保存的编辑冲掉)\n"
    "async function refreshAvatars(){\n"
    "  const state = await api(\"/api/state\");\n"
    "  AVATARS = state.avatars || AVATARS;\n"
    "  renderAll();\n"
    "}\n"
    "\n"
    "async function save(){\n"
    "  await api(\"/api/config\", {method:\"POST\", body: JSON.stringify(model)});\n"
    "  toast(\"已保存到设备\");\n"
    "  await load();\n"
    "}\n"
    "\n"
    "byId(\"save\").onclick = () => save().catch(e => toast(\"保存失败：\" + e.message));\n"
    "byId(\"reload\").onclick = () => load().then(()=>toast(\"已重新载入\")).catch(e=>toast(e.message));\n"
    "// 与设备端 LOVE_EVENT_MAX 一致(24):设备记录一次要能塞进 NVS blob,也要让\n"
    "// 控制台/网页两个任务各自的 4KB、6KB 栈放得下一个 love_config_t。\n"
    "const EVENT_MAX = 24;\n"
    "\n"
    "byId(\"addEvent\").onclick = () => {\n"
    "  if(model.events.length >= EVENT_MAX){ toast(`最多 ${EVENT_MAX} 条事件`); return; }\n"
    "  const today = currentToday();\n"
    "  const iso = today.y + \"-\" + String(today.m).padStart(2,\"0\") + \"-\" + String(today.d).padStart(2,\"0\");\n"
    "  // category 显式给空串:让\"新加的这条确实没有分类\",而不是靠后端按同下标保留旧值。\n"
    "  model.events.push({name:\"新的纪念日\", icon:6, kind:0, date:iso, category:\"\", viewMode:0});\n"
    "  renderEvents(); renderPreview();\n"
    "};\n"
    "byId(\"start\").onchange = (e) => { model.start = e.target.value; renderPreview(); };\n"
    "byId(\"blankOff\").onchange = (e) => { model.blankOff = Number(e.target.value); };\n"
    "byId(\"bleEnabled\").onchange = (e) => { model.bleEnabled = e.target.value === \"1\"; };\n"
    "byId(\"nameA\").oninput = (e) => { model.people[0].name = e.target.value; renderPreview(); };\n"
    "byId(\"nameB\").oninput = (e) => { model.people[1].name = e.target.value; renderPreview(); };\n"
    "\n"
    "byId(\"syncTime\").onclick = async () => {\n"
    "  const epoch = Math.floor(Date.now()/1000);\n"
    "  try{\n"
    "    await api(\"/api/time\", {method:\"POST\", body: JSON.stringify({epoch})});\n"
    "    toast(\"已用手机时间对时\");\n"
    "    const state = await api(\"/api/state\"); renderTimeAndNet(state); renderPreview();\n"
    "  }catch(e){ toast(\"对时失败：\" + e.message); }\n"
    "};\n"
    "byId(\"scanBtn\").onclick = async () => {\n"
    "  toast(\"正在扫描…\");\n"
    "  try{\n"
    "    const data = await api(\"/api/scan\");\n"
    "    const list = byId(\"scanList\");\n"
    "    list.innerHTML = \"\";\n"
    "    if(!data.aps.length){ list.innerHTML = '<li class=\"muted\">没有扫描到网络</li>'; return; }\n"
    "    data.aps.forEach(ap => {\n"
    "      const li = document.createElement(\"li\");\n"
    "      li.innerHTML = `<span>${ap.ssid || \"(隐藏)\"}${ap.secure ? \" 🔒\" : \"\"}</span><span>${ap.rssi} dBm</span>`;\n"
    "      li.onclick = () => { byId(\"wifiSsid\").value = ap.ssid; toast(\"已填入 \" + ap.ssid); };\n"
    "      list.appendChild(li);\n"
    "    });\n"
    "    toast(`扫描完成，共 ${data.aps.length} 个`);\n"
    "  }catch(e){ toast(\"扫描失败：\" + e.message); }\n"
    "};\n"
    "byId(\"wifiSave\").onclick = async () => {\n"
    "  const ssid = byId(\"wifiSsid\").value.trim();\n"
    "  if(!ssid){ toast(\"请填写 Wi-Fi 名称\"); return; }\n"
    "  try{\n"
    "    await api(\"/api/wifi\", {method:\"POST\", body: JSON.stringify({ssid, pass: byId(\"wifiPass\").value})});\n"
    "    byId(\"wifiPass\").value = \"\";\n"
    "    toast(\"已保存，正在连接（状态会稍后刷新）\");\n"
    "    setTimeout(()=>load().catch(()=>{}), 2500);\n"
    "  }catch(e){ toast(\"保存失败：\" + e.message); }\n"
    "};\n"
    "byId(\"wifiClear\").onclick = async () => {\n"
    "  try{ await api(\"/api/wifi/clear\", {method:\"POST\", body:\"{}\"});\n"
    "       toast(\"已清除凭据，热点已打开\"); setTimeout(()=>load().catch(()=>{}), 1500);\n"
    "  }catch(e){ toast(\"清除失败：\" + e.message); }\n"
    "};\n"
    "byId(\"apOn\").onclick = async () => {\n"
    "  try{ await api(\"/api/ap\", {method:\"POST\", body: JSON.stringify({on:true})});\n"
    "       toast(\"热点已打开，5 分钟无操作自动关闭\"); setTimeout(()=>load().catch(()=>{}), 1200);\n"
    "  }catch(e){ toast(\"操作失败：\" + e.message); }\n"
    "};\n"
    "byId(\"apOff\").onclick = async () => {\n"
    "  try{ await api(\"/api/ap\", {method:\"POST\", body: JSON.stringify({on:false})});\n"
    "       toast(\"热点已关闭\"); setTimeout(()=>load().catch(()=>{}), 1200);\n"
    "  }catch(e){ toast(\"操作失败：\" + e.message); }\n"
    "};\n"
    "byId(\"pvMain\").onclick = () => showPreviewView(\"main\");\n"
    "byId(\"pvEvent\").onclick = () => showPreviewView(\"event\");\n"
    "\n"
    "load().catch(e => toast(\"读取设备状态失败：\" + e.message));\n"
    "setInterval(async () => {\n"
    "  try{ renderTimeAndNet(await api(\"/api/state\")); renderPreview(); }catch(e){}\n"
    "}, 10000);\n";
#define LOVE_ADMIN_JS_SIZE (sizeof(LOVE_ADMIN_JS) - 1)

